### ISSUE TITLE
Incorrect comparison of paths for namespace resolution

### ISSUE THREAD

**Issue by emrainey** [OpenCyphal/pydsdl#104]
When trying to defend against `/a/b/c.dsdl` from colliding with `/a/b/c/d.dsdl` it also stops `/a/b/cother/d.dsdl` since it compares with a `startswith` and not a full basename compare in https://github.com/OpenCyphal/pydsdl/blob/98453a4f29e2776817870159eda0e8a5bfb819a2/pydsdl/_namespace.py#L270

**Comment by thirtytwobits** [comment]
This fix will be available with version `1.21.1`
