### ISSUE TITLE
Support multi-package builds

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal/pydsdl#82]
When building complex software where several packages are contributing DSDL types the simplified check `_ensure_no_namespace_collisions` gets in the way where different types are contributed to a single namespace from different folder structures.

We should fix this check to only be concerned with conflicting types within namespaces and not the namespace folders themselves.

**Comment by pavel-kirienko** [comment]
We will need to fix the specification first: https://forum.opencyphal.org/t/remove-the-requirement-to-have-uniquely-named-top-level-dsdl-namespaces/1706

I found the rule to be unnecessarily limiting and unhelpful. I think it should be revised as you stated.
