### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/pydsdl#87]
Replace the https://github.com/OpenCyphal/pydsdl/blob/master/appveyor.yml file with and equivalent GitHub Actions workflow file and verify that the workflow is equivalent.

**Comment by silverv** [comment]
@clyde-johnston This is assigned to you, I don't have perms to assign (@pavel-kirienko)

**Comment by pavel-kirienko** [comment]
Done in https://github.com/OpenCyphal/pydsdl/pull/98
