### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal/pydsdl#90]
TLDR; update parsimonious to get around getargspec change in the inspect module.

**Comment by pavel-kirienko** [comment]
Would it be difficult to get rid of six.py while we're at it? I see that the latest version no longer requires it, but it happens to be the same version that requires the new regex library. The new library, however, appears to be largely API-compatible with the native `re` module, so it could be that replacing `import regex as re` with `import re` might be enough to make the latest release work for us.

**Comment by pavel-kirienko** [comment]
Also maybe we should rather patch Parsimonious itself? See https://github.com/erikrose/parsimonious/issues/231

**Comment by thirtytwobits** [comment]
Closing this but opening a new issue to track six and upstreaming the change.
